# Goal
string fire_id
geometry_msgs/Pose fire_location
float32 required_water_volume
float32 estimated_duration
---
# Result
bool success
string message
float32 water_used
float32 suppression_time_seconds
---
# Feedback
float32 progress
float32 remaining_water
